// Random album data that is added to Firestore
// After you've signed into Album Reviews, click the dropdown
// menu in the top right corner and select "Add sample albums"

export const randomData = {
  albumNames: [
    "Midnight Serenade",
    "Electric Dreams",
    "Urban Echoes",
    "Velvet Thunder",
    "Neon Nights",
    "Cosmic Waves",
    "Silent Revolution",
    "Golden Hour",
    "Dark Matter",
    "Crystal Visions",
    "Wildfire",
    "Ocean Breeze",
    "Mountain Peak",
    "Desert Storm",
    "City Lights",
    "Autumn Leaves",
    "Winter Solstice",
    "Spring Awakening",
    "Summer Heat",
    "Eternal Flame",
    "Broken Mirror",
    "Lost Horizon",
    "Final Chapter",
    "New Beginning",
    "Endless Journey",
    "Hidden Truth",
    "Open Sky",
    "Deep Blue",
    "Bright Future",
    "Ancient Echoes",
    "Modern Times",
    "Classic Revival",
    "Future Tense",
    "Past Present",
    "Now and Then",
    "Here and There",
    "Up and Down",
    "Inside Out",
    "Round and Round",
    "Back to Front",
    "Top to Bottom",
    "Left to Right",
    "All Around",
    "Far and Wide",
    "Near and Far",
    "High and Low",
  ],
  albumYears: [
    1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999,
    2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
    2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019,
    2020, 2021, 2022, 2023, 2024, 2025,
  ],
  albumGenres: [
    "Rock",
    "Pop",
    "Jazz",
    "Hip-Hop",
    "Electronic",
    "Country",
    "R&B",
    "Classical",
    "Metal",
    "Indie",
    "Folk",
    "Reggae",
    "Blues",
    "Punk",
    "Alternative",
    "Rap",
    "Soul",
    "Funk",
    "Disco",
    "EDM",
    "Techno",
    "House",
    "Trance",
    "K-Pop",
    "Latin",
    "World",
    "Gospel",
    "Bluegrass",
    "Americana",
  ],
  albumReviews: [
    { text: "This album is absolutely incredible! A masterpiece from start to finish.", rating: 5 },
    { text: "Perfect blend of melodies and lyrics. Can't stop listening!", rating: 5 },
    { text: "The production quality is outstanding. Every track is a gem.", rating: 5 },
    { text: "This album has been on repeat since I first heard it.", rating: 5 },
    { text: "A phenomenal musical experience that touches the soul.", rating: 5 },
    {
      text: "The artist's best work yet. Every song is perfectly crafted.",
      rating: 5,
    },
    { text: "Incredible vocals and instrumentation throughout.", rating: 5 },
    { text: "This album exceeded all my expectations. Pure brilliance.", rating: 5 },
    { text: "Great album with solid tracks and good production.", rating: 4 },
    { text: "Enjoyed listening to this, would recommend to others.", rating: 4 },
    { text: "Good collection of songs, some really stand out.", rating: 4 },
    { text: "Decent album, but some tracks are forgettable.", rating: 3 },
    { text: "It's okay, but nothing groundbreaking or memorable.", rating: 3 },
    { text: "The album was average, could have been better.", rating: 3 },
    {
      text: "Disappointing production and lackluster songwriting.",
      rating: 2,
    },
    { text: "Expected more from this artist, left feeling underwhelmed.", rating: 2 },
    { text: "Weak lyrics and repetitive melodies throughout.", rating: 2 },
    { text: "Not my cup of tea, couldn't connect with the music.", rating: 2 },
    {
      text: "Terrible album, waste of time. Would not recommend.",
      rating: 1,
    },
    {
      text: "One of the worst albums I've heard in recent memory.",
      rating: 1,
    },
    { text: "Poor quality production and uninspired songwriting.", rating: 1 },
    { text: "Completely unlistenable. Regret buying this.", rating: 1 },
    { text: "Simply outstanding! A musical masterpiece.", rating: 5 },
    { text: "Couldn't get enough of the amazing soundscapes.", rating: 5 },
    { text: "Top-notch musicianship, worth every listen.", rating: 5 },
    { text: "Highly recommended for music lovers.", rating: 5 },
    { text: "Exquisite arrangements that pleased my ears.", rating: 5 },
    { text: "A gem of an album, impeccable in every aspect.", rating: 5 },
    { text: "Excellent selection of tracks that flow perfectly.", rating: 5 },
    { text: "A fantastic listening experience overall.", rating: 5 },
    {
      text: "The atmosphere this album creates is perfect for relaxation.",
      rating: 4,
    },
    { text: "Good music, but some tracks could be improved.", rating: 4 },
    {
      text: "Pleasantly surprised by the variety of styles.",
      rating: 4,
    },
    { text: "Well-produced tracks with catchy melodies.", rating: 4 },
    { text: "Satisfying listen, suitable for background music.", rating: 4 },
    { text: "The album was okay, nothing special.", rating: 3 },
    {
      text: "Production could be better, but the songs are fine.",
      rating: 3,
    },
    {
      text: "An average experience, didn't leave a lasting impression.",
      rating: 3,
    },
    { text: "Expected more depth from the lyrics and composition.", rating: 2 },
    { text: "Mediocre songwriting and lackluster arrangements.", rating: 2 },
    {
      text: "Regret spending time on such a disappointing album.",
      rating: 2,
    },
    { text: "Not up to par with what I expected from this genre.", rating: 2 },
  ],
};
